### ISSUE TITLE
Audit mode

### ISSUE THREAD

**Issue by righettod** [riramar/hsecscan#13]
Hi,

First, thanks you very much for this very useful script and the amazing OWASP Security Headers project.

Do you that think that it will be possible to add a running mode to the script in order to allow to run it in a CI/CD process in order to give the following feedback to Dev + Ops teams in a JSON output:
* What are the missing security headers according to the OWASP Security Headers project recommendations?
* What are the misconfigured or too open configured security headers according to the OWASP Security Headers project recommendations?

Thanks you very much in advance :smiley:

**Comment by riramar** [comment]
- What are the missing security headers according to the OWASP Security Headers project recommendations?
Yes, that's the default output. I know some people are integrating with other tools like this one https://github.com/riramar/hsecscan/pull/11.

- What are the misconfigured or too open configured security headers according to the OWASP Security Headers project recommendations?
For now hsecscan doesn't detect that but it's in my https://github.com/riramar/hsecscan/blob/master/TODO.md.
