### ISSUE TITLE
Suggestion: what happens if the server certificate is not valid?

### ISSUE THREAD

**Issue by fernand0** [riramar/hsecscan#2]
Hello,

nice work!
Maybe you coud take into account certificate validation (SSL: CERTIFICATE_VERIFY_FAILED) because the program fails when such thing happens. Maybe this could be added as another information and try to do the other checks even the certificate is not valid.

Best regards!

**Comment by riramar** [comment]
Hi @fernand0 ,

Thanks for the feedback.
I had this same discussion (in portuguese here https://github.com/riramar/hsecscan/pull/1#issuecomment-152539080) and from what I saw on urlib2 docs (URL below) you should pass a cafile for certificate checking (hostname, expiration, revoke and signature).
So from my understanding and testing by default urlib2 doesn't check the certificate. It seems this is an environment configuration which means that you could have this enable in your environment.
I have a self-signed certificate in my personal page and I could check the headers using hasecscan, take a look:

```
$ ./hsecscan.py -u https://ricardo-iramar.com.br
>> RESPONSE INFO <<
URL: https://ricardo-iramar.com.br
Code: 200...
```

I also did the same testing using this URL https://testssl-expire.disig.sk with a valid certificate but a wrong hostname.

https://docs.python.org/2/library/urllib2.html
The optional cafile and capath parameters specify a set of trusted CA certificates for HTTPS requests. cafile should point to a single file containing a bundle of CA certificates, whereas capath should point to a directory of hashed certificate files. More information can be found in ssl.SSLContext.load_verify_locations().

**Comment by riramar** [comment]
Hi @fernand0 ,

Can I close this issue based on my previously comment?

Thanks
@riramar

**Comment by fernand0** [comment]
Hello,

sorry, I didn't find the time to test this again. You are true, now it seems to be working ok. I think I was testing with an incorrect version of the lib. You can close the issue and we will see what happens in the future.  
Thanks!

**Comment by riramar** [comment]
You're welcome @fernand0 !
